# Use a base Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python code and requirements file to the container
COPY requirements.txt .
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port your Flask app runs on (e.g., 5000)
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "app.py"]
